### ISSUE TITLE
question: is it safe to use it inside function

### ISSUE THREAD

**Issue by YousefAK009** [jinyus/lite_ref#14]
Is it safe to use someRef.of(context) inside any function like init state or/and onPressed callback?

It looks like the ref  will be registered and preserve the state until the whole widget is disposed

**Comment by zupat** [comment]
You'd have to use `addPostFrameCallback()` to use it in initState like Provider. Callbacks should be fine too. If you're using it after a future, you need to make sure that the widget is still mounted. 

All the rules regarding where you can use Provider; applies to lite_ref.
