### ISSUE TITLE
feat: Adding `exists` that allows you to know whether `ref` is already registered or not

### ISSUE THREAD

**Issue by YousefAK009** [jinyus/lite_ref#15]
**Description**

We use `controllerRef.of(context)` to register and obtain this item

But in widget children we want to register this `controllerRef`, but only if it already exists, or it displays the error “Provider Not Registered Yet”.

Example:

```dart

final postViewModelRef = Ref.scoped((context) => PostsViewModel());

class PostsViewModel with ChangeNotifier {

}

class PostsPage extends StatefulWidget{
 ...
}

class _PostsPageState extends State<PostsPage>{
    @override
    void initState() {
        super.initState();

        Future.microtask(() {
            // Here we register `postViewModelRef` to this context
            // also we fetch some data
            postViewModelRef.of(context).getFiltersDataFromApi();
        });

    }

    @override
    Widget build(BuildContext context) {
        ...
    }

     ...

    void navigateToFilterPage() {
        // logic for navigation
     }
}

class FilterPage extends StatelessWidget {

    @override
    Widget build(BuildContext context) {
        // `watch` is extension that throw `Provider Not Registered Yet`
        // if `postViewModelRef` not listening/registerd before
        // otherwise it will use `of` like usual 
        final vm = postViewModelRef.watch(context);

        ...
    }

}

extension <T> on ScopedRef<T> {

  T watch(BuildContext context) {

    if (!exists(context)) {
      throw ProviderNotRegisterdYet();
    }

    return of(context);
  }
}

````

**Comment by zupat** [comment]
Would `exists(context)` return "registered for this context" or "registered at all"?

**Comment by YousefAK009** [comment]
for this context,  so using `LiteRefScope` and overriding refs should return different results

```dart

 
@override
Widget build(BuildContext context) {
  // register it
  final vm = postViewModelRef.of(context); // ok

  return Column(
    children: [
      Builder(
        builder: (context) {
          // register it only if was exist before
          final vm = postViewModelRef.watch(context); // ok
        },
      ),
      LiteRefScope(
        overrides: [postViewModelRef],
        child: Builder(
          builder: (context) {
            // register it only if was exist before
            // this will fail and get `ProviderNotRegisteredYet` exception
            final vm = postViewModelRef.watch(context); // fail
          },
        ),
      ),
    ],
  );
}


```

**Comment by zupat** [comment]
I'm not really seeing the usecase but I'll add it none the less. 

Feel free to show me how it's useful...I'd really like to know

**Comment by YousefAK009** [comment]
This is very helpful in making the data flow unidirectional and helps in detecting errors very early

If you have a large project and you have several `ref` and in different places, you use `LiteRefScope` to obtain a fresh instance, here lies the problem and errors.

For example, I have `refs` that must initialize and obtain a data set before it can be used in other widgets. Therefore, when I use `watch` in child widgets, I am sure that I will use what I defined previously, and in case I forget to define it or do a refactor For the project and I forget to use `of` in the parent widget, the error will appear immediately, and therefore I will rearrange the code as appropriate.

```
App Widget(using `of` to initialize `db`, `firebase` ...)
│
├── Posts Widget(using `of` to initialize  `filterController` and using `watch` to obtain `firebase` )
│      │   
│      └── Filter Widget (using `watch` to obtain  `filterController`) // ok
│ 
└── Posts Widget(using `watch` to obtain `firebase` ) // and forget to initialize  filterController
        │   
        └── Filter Widget (using `watch` to obtain  `filterController`) // will fail, and I will fix it easly

```

**Comment by zupat** [comment]
I usually shy away from side-effect heavy code. 
I'd personally use a `Ref.asyncSingleton()` for objects that the entire app will use and are never disposed eg:  db,firebase etc. That coupled with a `FutureBuilder` that allows retries on failure.

```dart
class Database {
  Database();

  var _initialized = false;

  Future<void> init() async {
    if (_initialized) return;
    await Future.delayed(const Duration(seconds: 1));

    if (Random().nextInt(10) > 5) {
      throw Exception('Crashed');
    }

    _initialized = true;
  }
}

final dbRef = Ref.asyncSingleton(() async {
  final db = Database();
  await db.init();
  return db;
});

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: FutureBuilder(
        future: dbRef.instance,
        builder: (context, snapshot) {
          if (snapshot.connectionState != ConnectionState.done) {
            return CircularProgressIndicator();
          }

          if (snapshot.hasError) {
            return Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text('Initialization failed:\n${snapshot.error}'),
                TextButton(
                  onPressed: () {
                    setState(() {});
                  },
                  child: const Text('Retry'),
                ),
              ],
            );
          }

          return const Center(child: Text('App is ready'));
        },
      ),
    );
  }
}
```

**Comment by YousefAK009** [comment]
> I usually shy away from side-effect heavy code. I'd personally use a `Ref.asyncSingleton()` for objects that the entire app will use and are never disposed eg: db,firebase etc. That coupled with a `FutureBuilder` that allows retries on failure.


I got it, I just give an example of how to use unidirectional flow and have full control of that

**Comment by YousefAK009** [comment]
I have used Riverpod very extensively, and it has several serious problems. The first is that you can use `watch` from any widget in the project and you will not be able to control who owns this provider easily like when you use the normal Provider package. Although it has an `exists` function, it does not work in this way because of the way the Riverpod itself is designed.
Another problem is that you must write the entire statement every time you want to call this provider `ref.watch(....) / ref.read(.....)`, and if you define it in the global scope and use a variable of it, you will see some strange uses and behaviors.
For example, you write the following: "late final controller = ref.watch(controllerProvider);" In the Global State, it is a wild adventure that you do not want to be exposed to
