### ISSUE TITLE
Compatibility with Pure Dart Environments After Recent Updates

### ISSUE THREAD

**Issue by yehorh** [jinyus/lite_ref#9]
Hello,

After the recent updates, it appears that the DI package now has dependencies on Flutter, making it incompatible with pure Dart environments. This shift raises concerns about the future usability of the package for non-Flutter Dart projects.

Could you please clarify whether there are plans to maintain compatibility with pure Dart by splitting the package or offering a separate version for Dart environments? Or will the development focus solely on Flutter going forward?

Thank you for your package!

**Comment by zupat** [comment]
Thanks for the feedback. I was going to remove the global containers as global variables are usually considered an anti-pattern but decided to keep them as it wasn't too much trouble.

Since this is affecting users, I will split those out into a `lite_ref_core`  package that can be used for pure dart projects(later today).

I want to pose a question though, is there any use case (Outside of pure dart code) that `Ref.scope` doesn't cover for you?

**Comment by zupat** [comment]
Fixed:
lite_ref_core: https://pub.dev/packages/lite_ref_core

lite_ref: https://pub.dev/packages/lite_ref

**Comment by yehorh** [comment]
> Thanks for the feedback. I was going to remove the global containers as global variables are usually considered an anti-pattern but decided to keep them as it wasn't too much trouble.
> 
> Since this is affecting users, I will split those out into a `lite_ref_core` package that can be used for pure dart projects(later today).
> 
> I want to pose a question though, is there any use case (Outside of pure dart code) that `Ref.scope` doesn't cover for you?

To be frank, I don't use this package in production apps, only in MVPs. The main idea of the package is great, but I am trying to understand the pros and cons for me, and how to use it with different state management approaches.

**Comment by zupat** [comment]
Fair enough, this is the base of dependency injection for my signals package: [state_beacon](https://github.com/jinyus/dart_beacon)

I'm always interested in how others are using it so feel free to create architectural issues/discussions.

**Comment by yehorh** [comment]
[state_beacon](https://github.com/jinyus/dart_beacon) Wow 😮, that looks a lot better than hyped `signals`.
Thanks for the link.

**Comment by yehorh** [comment]
@jinyus 
> I want to pose a question though, is there any use case (Outside of pure dart code) that Ref.scope doesn't cover for you?

I can't initialize async services with `Ref.scope`.

Singletons are an anti-pattern because they can't be replaced for test purposes, I thought, and lite_ref fixes it.

**Comment by zupat** [comment]
> I can't initialize async services with Ref.scope.

Fair enough.

> I thought, and lite_ref fixes it

It does, but things like concurrent testing is still not possible. 
The main issue that `ScopedRef` solves is providing disposables. It needs to be tied to the widget lifecycle so it knows when all widgets that use the instance are unmounted. This isn't possible with singletons/GetIT.

For things like databases, api clients etc...singletons are fine.
